### ISSUE TITLE
The Html code is not minified

### ISSUE THREAD

**Issue by MusicalityMaker** [WyriHaximus/MinifyHtml#2]
Hello,

I tried your plugin. The problem is my code is not midifed.

First, I load the plugin in my bootstrap file 
```
Plugin::loadAll([
    'WyriHaximus/MinifyHtml' => ['bootstrap' => true]
]);
```

Second, i load the helper in my AppView file 
```
public function initialize()
    {
        $this->loadHelper('WyriHaximus/MinifyHtml.MinifyHtml');
    }
```

Thank your of your answer.

**Comment by WyriHaximus** [comment]
By default the plugin doesn't minify when debug mode is on. [There is a setting to override that for development.](https://github.com/WyriHaximus/MinifyHtml/blob/master/config/config.sample.php#L6)

**Comment by WyriHaximus** [comment]
Assuming my previous comment solved your problem so closing this issue.
