### ISSUE TITLE
Error compress Html with Japanese characters

### ISSUE THREAD

**Issue by anhtuank7c** [WyriHaximus/MinifyHtml#3]
My HTML contain Japanese characters, and when use both 2 kind of factory, the Japanese characters going to "???".

See image:

![](http://i.imgur.com/oMa7Z1f.png)

**Comment by WyriHaximus** [comment]
Interesting, that isn't supposed to happen, can you give my your PHP version, the Japanese characters that are supposed to be there, and the uncompressed HTML of the snippet visible so I can add an edge case for it in the tests?

**Comment by anhtuank7c** [comment]
Uncompressed HTML can download at here: [https://www.dropbox.com/s/uohhz84cz3tjlhz/Desktop.zip?dl=0]

My PHP version: 5.5.12.

![Detail](http://i.imgur.com/5xS3hI9.png)

**Comment by WyriHaximus** [comment]
Thanks! Looks like the javascript minification it throwing things off, for now you can try the `Factory::constructFastest`. It only compresses the HTML and leaves CSS and JS intact.

**Comment by anhtuank7c** [comment]
This is cause from application encoding.
Not your's :-1: 
I'm sorry.
Please forget it.

**Comment by WyriHaximus** [comment]
No worries, I still have it open as a edge cause, what application encoding where you using and what are you using? Might still included it in the test cause as the issue it self was caused by one of the javascript compressors.

**Comment by anhtuank7c** [comment]
My application encoding: euc-jp

**Comment by WyriHaximus** [comment]
Cheers, thank you :)
