### ISSUE TITLE
chronos 2.0 has been released

### ISSUE THREAD

**Issue by mirko-pagliai** [WyriHaximus/MinifyHtml#35]
https://github.com/WyriHaximus/MinifyHtml/blob/20dc005af793109b8ca59c99b40614cd70e5744f/composer.json#L24

`chronos` 2.0 has been released. Is it possible to fix?

**Comment by WyriHaximus** [comment]
Sure, hold on

**Comment by WyriHaximus** [comment]
Resolved through 0c0967fc2cf15240d18b59150feae33e29959973
