### ISSUE TITLE
Remove version of asset files

### ISSUE THREAD

**Issue by anhtuank7c** [WyriHaximus/MinifyHtml#5]
Dear WyriHaximus.
In CakePHP 3 has configure:
```
    /**
     * Apply timestamps with the last modified time to static assets (js, css, images).
     * Will append a querystring parameter containing the time the file was modified.
     * This is useful for busting browser caches.
     *
     * Set to true to apply timestamps when debug is true. Set to 'force' to always
     * enable timestamping regardless of debug value.
     */
    'Asset' => [
        'timestamp' => true,
    ],
```

But when using this plugin, the Asset timestamp auto remove too. `/css/style.css`
The goal i want to be: `/css/style.css?1453088025`
When not use plugin, its work normally.
Thanks.

**Comment by WyriHaximus** [comment]
Interesting, I'll have a look at it shortly. This isn't something that is intended to happen though

**Comment by anhtuank7c** [comment]
Hi @WyriHaximus 
How it's going?

**Comment by WyriHaximus** [comment]
Seems that PR is fine and the time stamp isn't affected. Is this currently still an issue if you run the following two commands?:

```bash
composer update wyrihaximus/minify-html
composer update wyrihaximus/html-compress
```

If it isn't could you share a page where this happens (feel free to send an email to the address on my github profile if you prefer to keep it out of public record).

**Comment by anhtuank7c** [comment]
Thanks @WyriHaximus 
It's ok.
Just remember to set `Asset.timestamp = force`

**Comment by WyriHaximus** [comment]
Great, good to hear you solved it :+1: !
