### ISSUE TITLE
Details please :) 

### ISSUE THREAD

**Issue by neuropass** [WyriHaximus/MinifyHtml#7]
Hi,

I started using your plugin, however would you be so kind to provide some detailed info on what it does under the hood? Would be also easier to identify bugs if any this way.
For example does your plugin performs the following?

1-Remove HTML comments. 
2-Remove slash in self closing elements. /> becomes >.
3-Remove type="text/css" and type="text/javascript" in style and script tags.
4-Minimize elements within <head></head>. It will not keep any whitespace (except inside script).
5-Minimize elements within <body></body> but keep spaces between tags to preserve inline data 
6-Minimize inline SVG files (which are a bunch of XML tags).
7-Minimize Custom Elements. They look like this: <my-element>My content</my-element>.
8-Skip code, pre, script and textarea from being minified.

what about:
-remove CDATA tags?
-JSON support?

any options? for example what does it do for:
textarea, code, pre and script?

less ? more? 
Thanks again in advance!

**Comment by WyriHaximus** [comment]
I'll answer this in https://github.com/WyriHaximus/HtmlCompress/issues/36
